### ISSUE TITLE
Some messages are corrupted in django.po file

### ISSUE THREAD

**Issue by piotrrepetowski** [ocadotechnology/rapid-router#754]
I have noticed that some long messages are corrupted. Consider line 382 in django.po downloaded from CrowdIn.

in django.po there is:
"This path looks a bit like a four leaf clover. Can you take the driver "
while it should be:
"This path looks a bit like a four leaf clover. Can you take the driver through it?"

Django's makemessages splits keys into multiple lines e.g.

#: messages.py:560
msgid ""
"This path looks a bit like a four leaf clover. Can you take the driver "
"through it? "
msgstr ""

Maybe we should use --no-wrap before it worked without this though.

**Comment by mikebryant** [comment]
It looks like crowdin doesn't support the wrapped lines Django generates by default.
Not sure how this worked before - possibly it was different with manual uploads vs crowdin api uploads?

I'm putting a fix in now with --no-wrap, that should fix the issue

**Comment by piotrrepetowski** [comment]
:thumbsup:

**Comment by piotrrepetowski** [comment]
The problem still exists, after deploying the version with '--no-wrap'.

See the travis log: https://travis-ci.org/ocadotechnology/rapid-router/jobs/124702575#L2473 (line 2473)

I suppose "skipped" means that nothing has changed and when you look at revisions of django.po in CrowdIn you'll see that nothing has changed since Apr 20, 2016 20:16 (excluding my manual update, see below).

When I run the following commands on my local machine:
`mkdir -p game/locale`
`cd game && django-admin makemessages -l en_GB --no-wrap && cd -`
`crowdin-cli-py upload sources`
I got: 
`Updating source file: game/locale/en_GB/LC_MESSAGES/django.po - updated`

And the new revision 6 was registered on CrowdIn. The new version contains proper messages.

Could it be a some difference between my local machine and travis?

`crowdin-cli-py --version`
returns
`crowdin-cli-py 0.95.3` - which is exactly the same as in travis.

`django-admin --version`
returns
`1.8.2`

I wonder what will happen after the next travis build. Will it overwrite django.po uploaded by me?

**Comment by mikebryant** [comment]
Travis will most likely overwrite it. I can see the problem in the downloaded archives from Pypi too 

It works locally for me too, I'm not sure what the difference is between our local environments and the one in Travis

**Comment by mikebryant** [comment]
Default `xgettext` version on travis is `0.18.1` - version on my desktop is `0.18.3`
Changelog for `xgettext` version `0.18.3` reveals: `xgettext now also
    supports explicit string concatenation with '+' `

(translation message extraction doesn't run python code - From the docs: `The caveat with using variables or computed values, as in the previous two examples, is that Django’s translation-string-detecting utility, django-admin makemessages, won’t be able to find these strings.`)

I'll look at getting travis to upgrade the `xgettext` version, so it understands concatenation with `+`

**Comment by mikebryant** [comment]
Ok, 0.18.3 doesn't appear to be available in precise.. *pondering*

**Comment by mikebryant** [comment]
Gonna try the trusty beta infrastructure

**Comment by mikebryant** [comment]
Ok, let's confirm this works..

**Comment by piotrrepetowski** [comment]
Looks good

**Comment by mikebryant** [comment]
Awesome. I think we're good for now then
